apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstapp
  labels:
    app: firstapp
spec:
  selector:
    matchLabels:
      app: firstapp
  template:
    metadata:
      labels:
        app: firstapp
    spec:
      containers:
      - name: frontend
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: debian
        image: debian
        command: ["sleep", "3600"]
